name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node.js App to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Create ZIP for Deployment
        run: zip -r app.zip . -x "*.git*" "node_modules/*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-ap-south-1/hospital/app-${{ github.sha }}.zip

      - name: Create New EB Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "hospital" \
            --version-label "build-${{ github.sha }}" \
            --source-bundle S3Bucket="elasticbeanstalk-ap-south-1",S3Key="hospital/app-${{ github.sha }}.zip"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "Hospital-env" \
            --version-label "build-${{ github.sha }}"
